/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Actor: typeof import('./src/components/Actor.vue')['default']
    Genre: typeof import('./src/components/Genre.vue')['default']
    Genre_old: typeof import('./src/components/Genre_old.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Movie: typeof import('./src/components/Movie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
