version: "3.8"
services:
  movietrackerdb:
    container_name: movietrackerdb
    image: postgres:14-alpine
    ports:
      - 5434:5432
    volumes:
      - ~/apps/postgres:/data/db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movietrackerdb
